# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Guild Wars 2 LGBT Alliance
email: admin@gw2.lgbt
description: > # this means to ignore newlines until "baseurl:"
  An alliance of intersectional Guild Wars 2 Guilds and our allies.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gw2-lgbt-alliance.gitlab.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
exclude: ["README.md"]